package services

import models.{Category => CCategory}

object DeNoPaTranSMARTMapping {

  val demographics = new CCategory("Demographics")

  // Tests
  val mmseTest = new CCategory("PSP. MMSE (Folstein Mini-Mental State Exam)")
  val clockDrawingTest = new CCategory("Clock Drawing Test")
  val mdsUPDRSTest = new CCategory("MDS-UPDRS - Part I to Part IV")
  val hYTest = new CCategory("H&Y (Hoehn and Yahr")
  val nmsPDTest = new CCategory("NMS-PD (Non-Movement Problems in Parkinson's)")
  val moCaTest = new CCategory("MoCA (Montreal Cognitive Assessment Test)")
  val pdssTest = new CCategory("PDSS (Parkinson's Disease Sleep Scale)")
  val essTest = new CCategory("ESS (Epworth Sleepiness Scale)")
  val remSleepTest = new CCategory("Similar (13 Qs): REM Sleep Behavior Disorder Screening Questionnaire")

  val subjectsData = new CCategory("Subjects").addChildren(List(demographics))
  val motorTest = new CCategory("Motor").addChildren(List(mdsUPDRSTest, hYTest))
  val nonmotorTest = new CCategory("NonMotor").addChildren(List(mmseTest, clockDrawingTest, nmsPDTest, moCaTest, pdssTest, essTest, remSleepTest))
  val clinicalData = new CCategory("Clinical Data").addChildren(List(motorTest, nonmotorTest))

  val rootCategory = new CCategory("").addChildren(List(subjectsData, clinicalData))

  val fieldCategoryMap = Map(
    "Geb_Datum" -> demographics,
    "Geschlecht" -> demographics,
    "b_Gruppe" -> demographics,
    "a_CRF_Schuljahre" -> demographics,
    "a_CRF_MMST_1_1" -> mmseTest,
    "a_CRF_MMST_1_2" -> mmseTest,
    "a_CRF_MMST_1_3" -> mmseTest,
    "a_CRF_MMST_1_4" -> mmseTest,
    "a_CRF_MMST_1_5" -> mmseTest,
    "a_CRF_MMST_2_1" -> mmseTest,
    "a_CRF_MMST_2_2" -> mmseTest,
    "a_CRF_MMST_2_3" -> mmseTest,
    "a_CRF_MMST_2_4" -> mmseTest,
    "a_CRF_MMST_2_5" -> mmseTest,
    "a_CRF_MMST_3" -> mmseTest,
    "a_CRF_MMST_4" -> mmseTest,
    "a_CRF_MMST_5" -> mmseTest,
    "a_CRF_MMST_6" -> mmseTest,
    "a_CRF_MMST_7" -> mmseTest,
    "a_CRF_MMST_8" -> mmseTest,
    "a_CRF_MMST_9" -> mmseTest,
    "a_CRF_MMST_10" -> mmseTest,
    "a_CRF_MMST_11" -> mmseTest,
    "a_CRF_MMST_Summe" -> mmseTest,
    "a_CRF_MMST_Category" -> mmseTest,

    "a_CRF_Uhrentest" -> clockDrawingTest,

    "a_MDS_UPDRS_1a" -> mdsUPDRSTest,

    "a_MDS_UPDRS_1.1" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.2" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.3" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.4" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.5" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.6" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.6a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.7" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.8" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.9" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.10" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.11" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.12" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.13" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.1" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.2" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.3" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.4" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.5" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.6" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.7" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.8" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.9" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.10" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.11" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.12" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.13" -> mdsUPDRSTest,

    "a_MDS_UPDRS_3a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3c" -> mdsUPDRSTest,

    "a_MDS_UPDRS_3.1" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.2" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.3a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.3b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.3c" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.3d" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.3e" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.4a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.4b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.5a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.5b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.6a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.6b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.7a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.7b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.8a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.8b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.9" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.10" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.11" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.12" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.13" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.14" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.15a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.15b" -> mdsUPDRSTest,

    "a_MDS_UPDRS_3.16a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.16b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.17a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.17b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.17c" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.17d" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.17e" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.18" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3_Dyskinesien" -> mdsUPDRSTest,
    "a_MDS_UPDRS_4.1" -> mdsUPDRSTest,
    "a_MDS_UPDRS_4.2" -> mdsUPDRSTest,
    "a_MDS_UPDRS_4.3" -> mdsUPDRSTest,
    "a_MDS_UPDRS_4.4" -> mdsUPDRSTest,
    "a_MDS_UPDRS_4.5" -> mdsUPDRSTest,
    "a_MDS_UPDRS_4.6" -> mdsUPDRSTest,

    "a_MDS_UPDRS_1_sum" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2_sum" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3_sum" -> mdsUPDRSTest,
    "a_MDS_UPDRS_4_sum" -> mdsUPDRSTest,
    "a_MDS_UPDRS_sum" -> mdsUPDRSTest,

    "a_MDS_UPDRS_H_Y" -> hYTest,

  "a_PD_NMS_1" -> nmsPDTest,
  "a_PD_NMS_2" -> nmsPDTest,
  "a_PD_NMS_3" -> nmsPDTest,
  "a_PD_NMS_4" -> nmsPDTest,
  "a_PD_NMS_5" -> nmsPDTest,
  "a_PD_NMS_6" -> nmsPDTest,
  "a_PD_NMS_7" -> nmsPDTest,
  "a_PD_NMS_8" -> nmsPDTest,
  "a_PD_NMS_9" -> nmsPDTest,
  "a_PD_NMS_10" -> nmsPDTest,
  "a_PD_NMS_11" -> nmsPDTest,
  "a_PD_NMS_12" -> nmsPDTest,
  "a_PD_NMS_13" -> nmsPDTest,
  "a_PD_NMS_14" -> nmsPDTest,
  "a_PD_NMS_15" -> nmsPDTest,
  "a_PD_NMS_16" -> nmsPDTest,
  "a_PD_NMS_17" -> nmsPDTest,
  "a_PD_NMS_18" -> nmsPDTest,
  "a_PD_NMS_19" -> nmsPDTest,
  "a_PD_NMS_20" -> nmsPDTest,
  "a_PD_NMS_21" -> nmsPDTest,
  "a_PD_NMS_22" -> nmsPDTest,
  "a_PD_NMS_23" -> nmsPDTest,
  "a_PD_NMS_24" -> nmsPDTest,
  "a_PD_NMS_25" -> nmsPDTest,
  "a_PD_NMS_26" -> nmsPDTest,
  "a_PD_NMS_27" -> nmsPDTest,
  "a_PD_NMS_28" -> nmsPDTest,
  "a_PD_NMS_29" -> nmsPDTest,
  "a_PD_NMS_30" -> nmsPDTest,
  "a_PD_NMS_sum" -> nmsPDTest,
  "a_PD_NMS_mean" -> nmsPDTest,

  "a_MoCa_Exekutiv" -> moCaTest,
  "a_MoCa_Benennen" -> moCaTest,
  "a_MoCa_Aufmerksamkeit_Zahlenliste" ->moCaTest,
  "a_MoCa_Aufmerksamkeit_Buchstabenliste" -> moCaTest,
  "a_MoCa_Aufmerksamkeit_Abziehen" -> moCaTest,
  "a_MoCa_Sprache_Wiederholen" -> moCaTest,
  "a_MoCa_Sprache_FWoerter" -> moCaTest,
  "a_MoCa_Abstraktion" -> moCaTest,
  "a_MoCa_Erinnerung" -> moCaTest,
  "a_MoCa_Orientierung" -> moCaTest,
  "a_MoCa_Gesamt" -> moCaTest,

  "a_PDSS_1" -> pdssTest,
  "a_PDSS_2" -> pdssTest,
  "a_PDSS_3" -> pdssTest,
  "a_PDSS_4" -> pdssTest,
  "a_PDSS_5" -> pdssTest,
  "a_PDSS_6" -> pdssTest,
  "a_PDSS_7" -> pdssTest,
  "a_PDSS_8" -> pdssTest,
  "a_PDSS_9" -> pdssTest,
  "a_PDSS_10" -> pdssTest,
  "a_PDSS_11" -> pdssTest,
  "a_PDSS_12" -> pdssTest,
  "a_PDSS_13" -> pdssTest,
  "a_PDSS_14" -> pdssTest,
  "a_PDSS_15" -> pdssTest,
  "a_PDSS_sum" -> pdssTest,
  "a_PDSS_mean" -> pdssTest,

  "a_ESS_1" -> essTest,
  "a_ESS_2" -> essTest,
  "a_ESS_3" -> essTest,
  "a_ESS_4" -> essTest,
  "a_ESS_5" -> essTest,
  "a_ESS_6" -> essTest,
  "a_ESS_7" -> essTest,
  "a_ESS_8" -> essTest,
  "a_ESS_sum" -> essTest,
  "a_ESS_mean" -> essTest,

  "a_RBD_SQ_1" -> remSleepTest,
  "a_RBD_SQ_2" -> remSleepTest,
  "a_RBD_SQ_3" -> remSleepTest,
  "a_RBD_SQ_4" -> remSleepTest,
  "a_RBD_SQ_5" -> remSleepTest,
  "a_RBD_SQ_6.1" -> remSleepTest,
  "a_RBD_SQ_6.2" -> remSleepTest,
  "a_RBD_SQ_6.1" -> remSleepTest,
  "a_RBD_SQ_6.2" -> remSleepTest,
  "a_RBD_SQ_6.3" -> remSleepTest,
  "a_RBD_SQ_6.4" -> remSleepTest,
  "a_RBD_SQ_7" -> remSleepTest,
  "a_RBD_SQ_7" -> remSleepTest,
  "a_RBD_SQ_8" -> remSleepTest,
  "a_RBD_SQ_9" -> remSleepTest,
  "a_RBD_SQ_10" -> remSleepTest,
  "a_RBD_SQ_sum" -> remSleepTest,
  "a_RBD_SQ_mean" -> remSleepTest
  )

  val fieldLabelMap = Map(
    "Geb_Datum" -> "Birthday",
    "Geschlecht" -> "Gender",
    "b_Gruppe" -> "Group",
    "a_CRF_Schuljahre" -> "School Year",
    "a_CRF_MMST_1_1" -> "MMST_1_1",
    "a_CRF_MMST_1_2" -> "MMST_1_2",
    "a_CRF_MMST_1_3" -> "MMST_1_3",
    "a_CRF_MMST_1_4" -> "MMST_1_4",
    "a_CRF_MMST_1_5" -> "MMST_1_5",
    "a_CRF_MMST_2_1" -> "MMST_2_1",
    "a_CRF_MMST_2_2" -> "MMST_2_2",
    "a_CRF_MMST_2_3" -> "MMST_2_3",
    "a_CRF_MMST_2_4" -> "MMST_2_4",
    "a_CRF_MMST_2_5" -> "MMST_2_5",
    "a_CRF_MMST_3" -> "MMST_3",
    "a_CRF_MMST_4" -> "MMST_4",
    "a_CRF_MMST_5" -> "MMST_5",
    "a_CRF_MMST_6" -> "MMST_6",
    "a_CRF_MMST_7" -> "MMST_7",
    "a_CRF_MMST_8" -> "MMST_8",
    "a_CRF_MMST_9" -> "MMST_9",
    "a_CRF_MMST_10" -> "MMST_10",
    "a_CRF_MMST_11" -> "MMST_11",
    "a_CRF_MMST_Summe" -> "MMST_Sum",
    "a_CRF_MMST_Category" -> "MMST_Category",

    "a_CRF_Uhrentest" -> "Clock Drawing Test",

    "a_MDS_UPDRS_1a" -> "UPDRS_1a",
    "a_MDS_UPDRS_1.1" -> "UPDRS_1.1",
    "a_MDS_UPDRS_1.2" -> "UPDRS_1.2",
    "a_MDS_UPDRS_1.3" -> "UPDRS_1.3",
    "a_MDS_UPDRS_1.4" -> "UPDRS_1.4",
    "a_MDS_UPDRS_1.5" -> "UPDRS_1.5",
    "a_MDS_UPDRS_1.6" -> "UPDRS_1.6",
    "a_MDS_UPDRS_1.6a" -> "UPDRS_1.6a",
    "a_MDS_UPDRS_1.7" -> "UPDRS_1.7",
    "a_MDS_UPDRS_1.8" -> "UPDRS_1.8",
    "a_MDS_UPDRS_1.9" -> "UPDRS_1.9",
    "a_MDS_UPDRS_1.10" -> "UPDRS_1.10",
    "a_MDS_UPDRS_1.11" -> "UPDRS_1.11",
    "a_MDS_UPDRS_1.12" -> "UPDRS_1.12",
    "a_MDS_UPDRS_1.13" -> "UPDRS_1.13",
    "a_MDS_UPDRS_2.1" -> "UPDRS_2.1",
    "a_MDS_UPDRS_2.2" -> "UPDRS_2.2",
    "a_MDS_UPDRS_2.3" -> "UPDRS_2.3",
    "a_MDS_UPDRS_2.4" -> "UPDRS_2.4",
    "a_MDS_UPDRS_2.5" -> "UPDRS_2.5",
    "a_MDS_UPDRS_2.6" -> "UPDRS_2.6",
    "a_MDS_UPDRS_2.7" -> "UPDRS_2.7",
    "a_MDS_UPDRS_2.8" -> "UPDRS_2.8",
    "a_MDS_UPDRS_2.9" -> "UPDRS_2.9",
    "a_MDS_UPDRS_2.10" -> "UPDRS_2.10",
    "a_MDS_UPDRS_2.11" -> "UPDRS_2.11",
    "a_MDS_UPDRS_2.12" -> "UPDRS_2.12",
    "a_MDS_UPDRS_2.13" -> "UPDRS_2.13",
    "a_MDS_UPDRS_3a" -> "UPDRS_3a",
    "a_MDS_UPDRS_3b" -> "UPDRS_3b",
    "a_MDS_UPDRS_3c" -> "UPDRS_3c",
    "a_MDS_UPDRS_3.1" -> "UPDRS_3.1",
    "a_MDS_UPDRS_3.2" -> "UPDRS_3.2",
    "a_MDS_UPDRS_3.3a" -> "UPDRS_3.3a",
    "a_MDS_UPDRS_3.3b" -> "UPDRS_3.3b",
    "a_MDS_UPDRS_3.3c" -> "UPDRS_3.3c",
    "a_MDS_UPDRS_3.3d" -> "UPDRS_3.3d",
    "a_MDS_UPDRS_3.3e" -> "UPDRS_3.3e",
    "a_MDS_UPDRS_3.4a" -> "UPDRS_3.4a",
    "a_MDS_UPDRS_3.4b" -> "UPDRS_3.4b",
    "a_MDS_UPDRS_3.5a" -> "UPDRS_3.5a",
    "a_MDS_UPDRS_3.5b" -> "UPDRS_3.5b",
    "a_MDS_UPDRS_3.6a" -> "UPDRS_3.6a",
    "a_MDS_UPDRS_3.6b" -> "UPDRS_3.6b",
    "a_MDS_UPDRS_3.7a" -> "UPDRS_3.7a",
    "a_MDS_UPDRS_3.7b" -> "UPDRS_3.7b",
    "a_MDS_UPDRS_3.8a" -> "UPDRS_3.8a",
    "a_MDS_UPDRS_3.8b" -> "UPDRS_3.8b",
    "a_MDS_UPDRS_3.9" -> "UPDRS_3.9",
    "a_MDS_UPDRS_3.10" -> "UPDRS_3.10",
    "a_MDS_UPDRS_3.11" -> "UPDRS_3.11",
    "a_MDS_UPDRS_3.12" -> "UPDRS_3.12",
    "a_MDS_UPDRS_3.13" -> "UPDRS_3.13",
    "a_MDS_UPDRS_3.14" -> "UPDRS_3.14",
    "a_MDS_UPDRS_3.15a" -> "UPDRS_3.15a",
    "a_MDS_UPDRS_3.15b" -> "UPDRS_3.15b",
    "a_MDS_UPDRS_3.16a" -> "UPDRS_3.16a",
    "a_MDS_UPDRS_3.16b" -> "UPDRS_3.16b",
    "a_MDS_UPDRS_3.17a" -> "UPDRS_3.17a",
    "a_MDS_UPDRS_3.17b" -> "UPDRS_3.17b",
    "a_MDS_UPDRS_3.17c" -> "UPDRS_3.17c",
    "a_MDS_UPDRS_3.17d" -> "UPDRS_3.17d",
    "a_MDS_UPDRS_3.17e" -> "UPDRS_3.17e",
    "a_MDS_UPDRS_3.18" -> "UPDRS_3.18",
    "a_MDS_UPDRS_3_Dyskinesien" -> "UPDRS_3_Dyskinesias",
    "a_MDS_UPDRS_4.1" -> "UPDRS_4.1",
    "a_MDS_UPDRS_4.2" -> "UPDRS_4.2",
    "a_MDS_UPDRS_4.3" -> "UPDRS_4.3",
    "a_MDS_UPDRS_4.4" -> "UPDRS_4.4",
    "a_MDS_UPDRS_4.5" -> "UPDRS_4.5",
    "a_MDS_UPDRS_4.6" -> "UPDRS_4.6",

    "a_MDS_UPDRS_1_sum" -> "UPDRS_1_sum",
    "a_MDS_UPDRS_2_sum" -> "UPDRS_2_sum",
    "a_MDS_UPDRS_3_sum" -> "UPDRS_3_sum",
    "a_MDS_UPDRS_4_sum" -> "UPDRS_4_sum",
    "a_MDS_UPDRS_sum" -> "UPDRS_sum",
//
//    "a_MDS_UPDRS_H_Y" -> hYTest,
//
//    "a_PD_NMS_1" -> nmsPDTest,
//    "a_PD_NMS_2" -> nmsPDTest,
//    "a_PD_NMS_3" -> nmsPDTest,
//    "a_PD_NMS_4" -> nmsPDTest,
//    "a_PD_NMS_5" -> nmsPDTest,
//    "a_PD_NMS_6" -> nmsPDTest,
//    "a_PD_NMS_7" -> nmsPDTest,
//    "a_PD_NMS_8" -> nmsPDTest,
//    "a_PD_NMS_9" -> nmsPDTest,
//    "a_PD_NMS_10" -> nmsPDTest,
//    "a_PD_NMS_11" -> nmsPDTest,
//    "a_PD_NMS_12" -> nmsPDTest,
//    "a_PD_NMS_13" -> nmsPDTest,
//    "a_PD_NMS_14" -> nmsPDTest,
//    "a_PD_NMS_15" -> nmsPDTest,
//    "a_PD_NMS_16" -> nmsPDTest,
//    "a_PD_NMS_17" -> nmsPDTest,
//    "a_PD_NMS_18" -> nmsPDTest,
//    "a_PD_NMS_19" -> nmsPDTest,
//    "a_PD_NMS_20" -> nmsPDTest,
//    "a_PD_NMS_21" -> nmsPDTest,
//    "a_PD_NMS_22" -> nmsPDTest,
//    "a_PD_NMS_23" -> nmsPDTest,
//    "a_PD_NMS_24" -> nmsPDTest,
//    "a_PD_NMS_25" -> nmsPDTest,
//    "a_PD_NMS_26" -> nmsPDTest,
//    "a_PD_NMS_27" -> nmsPDTest,
//    "a_PD_NMS_28" -> nmsPDTest,
//    "a_PD_NMS_29" -> nmsPDTest,
//    "a_PD_NMS_30" -> nmsPDTest,
//    "a_PD_NMS_sum" -> nmsPDTest,
//    "a_PD_NMS_mean" -> nmsPDTest,

    "a_MoCa_Exekutiv" -> "MoCa Executive",
    "a_MoCa_Benennen" -> "MoCa Name",
    "a_MoCa_Aufmerksamkeit_Zahlenliste" -> "MoCa Number List",
    "a_MoCa_Aufmerksamkeit_Buchstabenliste" -> "MoCa Attention Number List" ,
    "a_MoCa_Aufmerksamkeit_Abziehen" -> "MoCa Subtracted Attention Test",
    "a_MoCa_Sprache_Wiederholen" -> "MoCa Language Repeat",
    "a_MoCa_Sprache_FWoerter" -> "MoCa Language F Words",
    "a_MoCa_Abstraktion" -> "MoCa Abstraction",
    "a_MoCa_Erinnerung" -> "MoCa Memory",
    "a_MoCa_Orientierung" -> "MoCa Orientation",
    "a_MoCa_Gesamt" -> "MoCa Sum"

//    "a_PDSS_1" -> pdssTest,
//    "a_PDSS_2" -> pdssTest,
//    "a_PDSS_3" -> pdssTest,
//    "a_PDSS_4" -> pdssTest,
//    "a_PDSS_5" -> pdssTest,
//    "a_PDSS_6" -> pdssTest,
//    "a_PDSS_7" -> pdssTest,
//    "a_PDSS_8" -> pdssTest,
//    "a_PDSS_9" -> pdssTest,
//    "a_PDSS_10" -> pdssTest,
//    "a_PDSS_11" -> pdssTest,
//    "a_PDSS_12" -> pdssTest,
//    "a_PDSS_13" -> pdssTest,
//    "a_PDSS_14" -> pdssTest,
//    "a_PDSS_15" -> pdssTest,
//    "a_PDSS_sum" -> pdssTest,
//    "a_PDSS_mean" -> pdssTest,
//
//    "a_ESS_1" -> essTest,
//    "a_ESS_2" -> essTest,
//    "a_ESS_3" -> essTest,
//    "a_ESS_4" -> essTest,
//    "a_ESS_5" -> essTest,
//    "a_ESS_6" -> essTest,
//    "a_ESS_7" -> essTest,
//    "a_ESS_8" -> essTest,
//    "a_ESS_sum" -> essTest,
//    "a_ESS_mean" -> essTest,
//
//    "a_RBD_SQ_1" -> remSleepTest,
//    "a_RBD_SQ_2" -> remSleepTest,
//    "a_RBD_SQ_3" -> remSleepTest,
//    "a_RBD_SQ_4" -> remSleepTest,
//    "a_RBD_SQ_5" -> remSleepTest,
//    "a_RBD_SQ_6.1" -> remSleepTest,
//    "a_RBD_SQ_6.2" -> remSleepTest,
//    "a_RBD_SQ_6.1" -> remSleepTest,
//    "a_RBD_SQ_6.2" -> remSleepTest,
//    "a_RBD_SQ_6.3" -> remSleepTest,
//    "a_RBD_SQ_6.4" -> remSleepTest,
//    "a_RBD_SQ_7" -> remSleepTest,
//    "a_RBD_SQ_7" -> remSleepTest,
//    "a_RBD_SQ_8" -> remSleepTest,
//    "a_RBD_SQ_9" -> remSleepTest,
//    "a_RBD_SQ_10" -> remSleepTest,
//    "a_RBD_SQ_sum" -> remSleepTest,
//    "a_RBD_SQ_mean" -> remSleepTest
  )
}