package runnables.denopa

import org.ada.server.models.Category

object DeNoPaBaselineTranSMARTMapping {

  val demographics = new Category("Demographics")

  // Tests
  val mmseTest = new Category("PSP. MMSE (Folstein Mini-Mental State Exam)")
  val clockDrawingTest = new Category("Clock Drawing Test")
  val mdsUPDRSTest = new Category("MDS-UPDRS - Part I to Part IV")
  val hYTest = new Category("H&Y (Hoehn and Yahr)")
  val nmsPDTest = new Category("NMS-PD (Non-Movement Problems in Parkinson's)")
  val moCaTest = new Category("MoCA (Montreal Cognitive Assessment Test)")
  val pdssTest = new Category("PDSS (Parkinson's Disease Sleep Scale)")
  val essTest = new Category("ESS (Epworth Sleepiness Scale)")
  val remSleepTest = new Category("Similar (13 Qs): REM Sleep Behavior Disorder Screening Questionnaire")

  val subjectsData = new Category("Subjects").setChildren(List(demographics))
  val motorTest = new Category("Motor").setChildren(List(mdsUPDRSTest, hYTest))
  val nonmotorTest = new Category("NonMotor").setChildren(List(mmseTest, clockDrawingTest, nmsPDTest, moCaTest, pdssTest, essTest, remSleepTest))
  val clinicalData = new Category("Clinical Data").setChildren(List(motorTest, nonmotorTest))

  val fieldCategoryMap = Map(
    "Geschlecht" -> demographics,
    "a_Alter" -> demographics,
    "Geb_Datum" -> demographics,
    "a_Gruppe" -> demographics,
    "a_CRF_Schuljahre" -> demographics,
    "a_CRF_MMST_1_1" -> mmseTest,
    "a_CRF_MMST_1_2" -> mmseTest,
    "a_CRF_MMST_1_3" -> mmseTest,
    "a_CRF_MMST_1_4" -> mmseTest,
    "a_CRF_MMST_1_5" -> mmseTest,
    "a_CRF_MMST_2_1" -> mmseTest,
    "a_CRF_MMST_2_2" -> mmseTest,
    "a_CRF_MMST_2_3" -> mmseTest,
    "a_CRF_MMST_2_4" -> mmseTest,
    "a_CRF_MMST_2_5" -> mmseTest,
    "a_CRF_MMST_3" -> mmseTest,
    "a_CRF_MMST_4" -> mmseTest,
    "a_CRF_MMST_5" -> mmseTest,
    "a_CRF_MMST_6" -> mmseTest,
    "a_CRF_MMST_7" -> mmseTest,
    "a_CRF_MMST_8" -> mmseTest,
    "a_CRF_MMST_9" -> mmseTest,
    "a_CRF_MMST_10" -> mmseTest,
    "a_CRF_MMST_11" -> mmseTest,
    "a_CRF_MMST_Summe" -> mmseTest,

    "a_CRF_Uhrentest" -> clockDrawingTest,

    "a_MDS_UPDRS_1a" -> mdsUPDRSTest,

    "a_MDS_UPDRS_1.1" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.2" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.3" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.4" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.5" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.6" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.6a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.7" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.8" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.9" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.10" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.11" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.12" -> mdsUPDRSTest,
    "a_MDS_UPDRS_1.13" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.1" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.2" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.3" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.4" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.5" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.6" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.7" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.8" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.9" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.10" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.11" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.12" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2.13" -> mdsUPDRSTest,

    "a_MDS_UPDRS_3a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3c" -> mdsUPDRSTest,

    "a_MDS_UPDRS_3.1" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.2" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.3a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.3b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.3c" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.3d" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.3e" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.4a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.4b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.5a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.5b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.6a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.6b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.7a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.7b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.8a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.8b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.9" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.10" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.11" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.12" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.13" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.14" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.15a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.15b" -> mdsUPDRSTest,

    "a_MDS_UPDRS_3.16a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.16b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.17a" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.17b" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.17c" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.17d" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.17e" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3.18" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3_Dyskinesien" -> mdsUPDRSTest,
    "a_MDS_UPDRS_4.1" -> mdsUPDRSTest,
    "a_MDS_UPDRS_4.2" -> mdsUPDRSTest,
    "a_MDS_UPDRS_4.3" -> mdsUPDRSTest,
    "a_MDS_UPDRS_4.4" -> mdsUPDRSTest,
    "a_MDS_UPDRS_4.5" -> mdsUPDRSTest,
    "a_MDS_UPDRS_4.6" -> mdsUPDRSTest,

    "a_MDS_UPDRS_1_sum" -> mdsUPDRSTest,
    "a_MDS_UPDRS_2_sum" -> mdsUPDRSTest,
    "a_MDS_UPDRS_3_sum" -> mdsUPDRSTest,
    "a_MDS_UPDRS_4_sum" -> mdsUPDRSTest,
    "a_MDS_UPDRS_sum" -> mdsUPDRSTest,

    "a_MDS_UPDRS_H_Y" -> hYTest,

    "a_PD_NMS_1" -> nmsPDTest,
    "a_PD_NMS_2" -> nmsPDTest,
    "a_PD_NMS_3" -> nmsPDTest,
    "a_PD_NMS_4" -> nmsPDTest,
    "a_PD_NMS_5" -> nmsPDTest,
    "a_PD_NMS_6" -> nmsPDTest,
    "a_PD_NMS_7" -> nmsPDTest,
    "a_PD_NMS_8" -> nmsPDTest,
    "a_PD_NMS_9" -> nmsPDTest,
    "a_PD_NMS_10" -> nmsPDTest,
    "a_PD_NMS_11" -> nmsPDTest,
    "a_PD_NMS_12" -> nmsPDTest,
    "a_PD_NMS_13" -> nmsPDTest,
    "a_PD_NMS_14" -> nmsPDTest,
    "a_PD_NMS_15" -> nmsPDTest,
    "a_PD_NMS_16" -> nmsPDTest,
    "a_PD_NMS_17" -> nmsPDTest,
    "a_PD_NMS_18" -> nmsPDTest,
    "a_PD_NMS_19" -> nmsPDTest,
    "a_PD_NMS_20" -> nmsPDTest,
    "a_PD_NMS_21" -> nmsPDTest,
    "a_PD_NMS_22" -> nmsPDTest,
    "a_PD_NMS_23" -> nmsPDTest,
    "a_PD_NMS_24" -> nmsPDTest,
    "a_PD_NMS_25" -> nmsPDTest,
    "a_PD_NMS_26" -> nmsPDTest,
    "a_PD_NMS_27" -> nmsPDTest,
    "a_PD_NMS_28" -> nmsPDTest,
    "a_PD_NMS_29" -> nmsPDTest,
    "a_PD_NMS_30" -> nmsPDTest,
    "a_PD_NMS_sum" -> nmsPDTest,
    "a_PD_NMS_mean" -> nmsPDTest,

    "a_MoCa_Exekutiv" -> moCaTest,
    "a_MoCa_Benennen" -> moCaTest,
    "a_MoCa_Aufmerksamkeit_Zahlenliste" ->moCaTest,
    "a_MoCa_Aufmerksamkeit_Buchstabenliste" -> moCaTest,
    "a_MoCa_Aufmerksamkeit_Abziehen" -> moCaTest,
    "a_MoCa_Sprache_Wiederholen" -> moCaTest,
    "a_MoCa_Sprache_FWoerter" -> moCaTest,
    "a_MoCa_Abstraktion" -> moCaTest,
    "a_MoCa_Erinnerung" -> moCaTest,
    "a_MoCa_Orientierung" -> moCaTest,
    "a_MoCa_Gesamt" -> moCaTest,

    "a_PDSS_1" -> pdssTest,
    "a_PDSS_2" -> pdssTest,
    "a_PDSS_3" -> pdssTest,
    "a_PDSS_4" -> pdssTest,
    "a_PDSS_5" -> pdssTest,
    "a_PDSS_6" -> pdssTest,
    "a_PDSS_7" -> pdssTest,
    "a_PDSS_8" -> pdssTest,
    "a_PDSS_9" -> pdssTest,
    "a_PDSS_10" -> pdssTest,
    "a_PDSS_11" -> pdssTest,
    "a_PDSS_12" -> pdssTest,
    "a_PDSS_13" -> pdssTest,
    "a_PDSS_14" -> pdssTest,
    "a_PDSS_15" -> pdssTest,
    "a_PDSS_sum" -> pdssTest,
    "a_PDSS_mean" -> pdssTest,

    "a_ESS_1" -> essTest,
    "a_ESS_2" -> essTest,
    "a_ESS_3" -> essTest,
    "a_ESS_4" -> essTest,
    "a_ESS_5" -> essTest,
    "a_ESS_6" -> essTest,
    "a_ESS_7" -> essTest,
    "a_ESS_8" -> essTest,
    "a_ESS_sum" -> essTest,
    "a_ESS_mean" -> essTest,

    "a_RBD_SQ_1" -> remSleepTest,
    "a_RBD_SQ_2" -> remSleepTest,
    "a_RBD_SQ_3" -> remSleepTest,
    "a_RBD_SQ_4" -> remSleepTest,
    "a_RBD_SQ_5" -> remSleepTest,
    "a_RBD_SQ_6.1" -> remSleepTest,
    "a_RBD_SQ_6.2" -> remSleepTest,
    "a_RBD_SQ_6.3" -> remSleepTest,
    "a_RBD_SQ_6.4" -> remSleepTest,
    "a_RBD_SQ_7" -> remSleepTest,
    "a_RBD_SQ_8" -> remSleepTest,
    "a_RBD_SQ_9" -> remSleepTest,
    "a_RBD_SQ_10" -> remSleepTest,
    "a_RBD_SQ_sum" -> remSleepTest,
    "a_RBD_SQ_mean" -> remSleepTest
  )

  val fieldLabelMap = Map(
    "Geschlecht" -> "Gender",
    "a_Alter" -> "Age",
    "Geb_Datum" -> "Birthday",
    "a_Gruppe" -> "Group",
    "a_CRF_Schuljahre" -> "School Year",
    "a_CRF_MMST_1_1" -> "MMST 1.1",
    "a_CRF_MMST_1_2" -> "MMST 1.2",
    "a_CRF_MMST_1_3" -> "MMST 1.3",
    "a_CRF_MMST_1_4" -> "MMST 1.4",
    "a_CRF_MMST_1_5" -> "MMST 1.5",
    "a_CRF_MMST_2_1" -> "MMST 2.1",
    "a_CRF_MMST_2_2" -> "MMST 2.2",
    "a_CRF_MMST_2_3" -> "MMST 2.3",
    "a_CRF_MMST_2_4" -> "MMST 2.4",
    "a_CRF_MMST_2_5" -> "MMST 2.5",
    "a_CRF_MMST_3" -> "MMST 3",
    "a_CRF_MMST_4" -> "MMST 4",
    "a_CRF_MMST_5" -> "MMST 5",
    "a_CRF_MMST_6" -> "MMST 6",
    "a_CRF_MMST_7" -> "MMST 7",
    "a_CRF_MMST_8" -> "MMST 8",
    "a_CRF_MMST_9" -> "MMST 9",
    "a_CRF_MMST_10" -> "MMST 10",
    "a_CRF_MMST_11" -> "MMST 11",
    "a_CRF_MMST_Summe" -> "MMST Sum",
    "a_CRF_MMST_Category" -> "MMST Category",

    "a_CRF_Uhrentest" -> "Clock Drawing Test",

    "a_MDS_UPDRS_1a" -> "MDS UPDRS 1a",
    "a_MDS_UPDRS_1.1" -> "MDS UPDRS 1.1",
    "a_MDS_UPDRS_1.2" -> "MDS UPDRS 1.2",
    "a_MDS_UPDRS_1.3" -> "MDS UPDRS 1.3",
    "a_MDS_UPDRS_1.4" -> "MDS UPDRS 1.4",
    "a_MDS_UPDRS_1.5" -> "MDS UPDRS 1.5",
    "a_MDS_UPDRS_1.6" -> "MDS UPDRS 1.6",
    "a_MDS_UPDRS_1.6a" -> "MDS UPDRS 1.6a",
    "a_MDS_UPDRS_1.7" -> "MDS UPDRS 1.7",
    "a_MDS_UPDRS_1.8" -> "MDS UPDRS 1.8",
    "a_MDS_UPDRS_1.9" -> "MDS UPDRS 1.9",
    "a_MDS_UPDRS_1.10" -> "MDS UPDRS 1.10",
    "a_MDS_UPDRS_1.11" -> "MDS UPDRS 1.11",
    "a_MDS_UPDRS_1.12" -> "MDS UPDRS 1.12",
    "a_MDS_UPDRS_1.13" -> "MDS UPDRS 1.13",
    "a_MDS_UPDRS_2.1" -> "MDS UPDRS 2.1",
    "a_MDS_UPDRS_2.2" -> "MDS UPDRS 2.2",
    "a_MDS_UPDRS_2.3" -> "MDS UPDRS 2.3",
    "a_MDS_UPDRS_2.4" -> "MDS UPDRS 2.4",
    "a_MDS_UPDRS_2.5" -> "MDS UPDRS 2.5",
    "a_MDS_UPDRS_2.6" -> "MDS UPDRS 2.6",
    "a_MDS_UPDRS_2.7" -> "MDS UPDRS 2.7",
    "a_MDS_UPDRS_2.8" -> "MDS UPDRS 2.8",
    "a_MDS_UPDRS_2.9" -> "MDS UPDRS 2.9",
    "a_MDS_UPDRS_2.10" -> "MDS UPDRS 2.10",
    "a_MDS_UPDRS_2.11" -> "MDS UPDRS 2.11",
    "a_MDS_UPDRS_2.12" -> "MDS UPDRS 2.12",
    "a_MDS_UPDRS_2.13" -> "MDS UPDRS 2.13",
    "a_MDS_UPDRS_3a" -> "MDS UPDRS 3a",
    "a_MDS_UPDRS_3b" -> "MDS UPDRS 3b",
    "a_MDS_UPDRS_3c" -> "MDS UPDRS 3c",
    "a_MDS_UPDRS_3.1" -> "MDS UPDRS 3.1",
    "a_MDS_UPDRS_3.2" -> "MDS UPDRS 3.2",
    "a_MDS_UPDRS_3.3a" -> "MDS UPDRS 3.3a",
    "a_MDS_UPDRS_3.3b" -> "MDS UPDRS 3.3b",
    "a_MDS_UPDRS_3.3c" -> "MDS UPDRS 3.3c",
    "a_MDS_UPDRS_3.3d" -> "MDS UPDRS 3.3d",
    "a_MDS_UPDRS_3.3e" -> "MDS UPDRS 3.3e",
    "a_MDS_UPDRS_3.4a" -> "MDS UPDRS 3.4a",
    "a_MDS_UPDRS_3.4b" -> "MDS UPDRS 3.4b",
    "a_MDS_UPDRS_3.5a" -> "MDS UPDRS 3.5a",
    "a_MDS_UPDRS_3.5b" -> "MDS UPDRS 3.5b",
    "a_MDS_UPDRS_3.6a" -> "MDS UPDRS 3.6a",
    "a_MDS_UPDRS_3.6b" -> "MDS UPDRS 3.6b",
    "a_MDS_UPDRS_3.7a" -> "MDS UPDRS 3.7a",
    "a_MDS_UPDRS_3.7b" -> "MDS UPDRS 3.7b",
    "a_MDS_UPDRS_3.8a" -> "MDS UPDRS 3.8a",
    "a_MDS_UPDRS_3.8b" -> "MDS UPDRS 3.8b",
    "a_MDS_UPDRS_3.9" -> "MDS UPDRS 3.9",
    "a_MDS_UPDRS_3.10" -> "MDS UPDRS 3.10",
    "a_MDS_UPDRS_3.11" -> "MDS UPDRS 3.11",
    "a_MDS_UPDRS_3.12" -> "MDS UPDRS 3.12",
    "a_MDS_UPDRS_3.13" -> "MDS UPDRS 3.13",
    "a_MDS_UPDRS_3.14" -> "MDS UPDRS 3.14",
    "a_MDS_UPDRS_3.15a" -> "MDS UPDRS 3.15a",
    "a_MDS_UPDRS_3.15b" -> "MDS UPDRS 3.15b",
    "a_MDS_UPDRS_3.16a" -> "MDS UPDRS 3.16a",
    "a_MDS_UPDRS_3.16b" -> "MDS UPDRS 3.16b",
    "a_MDS_UPDRS_3.17a" -> "MDS UPDRS 3.17a",
    "a_MDS_UPDRS_3.17b" -> "MDS UPDRS 3.17b",
    "a_MDS_UPDRS_3.17c" -> "MDS UPDRS 3.17c",
    "a_MDS_UPDRS_3.17d" -> "MDS UPDRS 3.17d",
    "a_MDS_UPDRS_3.17e" -> "MDS UPDRS 3.17e",
    "a_MDS_UPDRS_3.18" -> "MDS UPDRS 3.18",
    "a_MDS_UPDRS_3_Dyskinesien" -> "MDS UPDRS 3 Dyskinesias",
    "a_MDS_UPDRS_4.1" -> "MDS UPDRS 4.1",
    "a_MDS_UPDRS_4.2" -> "MDS UPDRS 4.2",
    "a_MDS_UPDRS_4.3" -> "MDS UPDRS 4.3",
    "a_MDS_UPDRS_4.4" -> "MDS UPDRS 4.4",
    "a_MDS_UPDRS_4.5" -> "MDS UPDRS 4.5",
    "a_MDS_UPDRS_4.6" -> "MDS UPDRS 4.6",

    "a_MDS_UPDRS_1_sum" -> "MDS UPDRS 1 Sum",
    "a_MDS_UPDRS_2_sum" -> "MDS UPDRS 2 Sum",
    "a_MDS_UPDRS_3_sum" -> "MDS UPDRS 3 Sum",
    "a_MDS_UPDRS_4_sum" -> "MDS UPDRS 4 Sum",
    "a_MDS_UPDRS_sum" -> "MDS UPDRS Sum",

    "a_MDS_UPDRS_H_Y" -> "MDS UPDRS H&Y",

    "a_PD_NMS_1" -> "NMS PD 1",
    "a_PD_NMS_2" -> "NMS PD 2",
    "a_PD_NMS_3" -> "NMS PD 3",
    "a_PD_NMS_4" -> "NMS PD 4",
    "a_PD_NMS_5" -> "NMS PD 5",
    "a_PD_NMS_6" -> "NMS PD 6",
    "a_PD_NMS_7" -> "NMS PD 7",
    "a_PD_NMS_8" -> "NMS PD 8",
    "a_PD_NMS_9" -> "NMS PD 9",
    "a_PD_NMS_10" -> "NMS PD 10",
    "a_PD_NMS_11" -> "NMS PD 11",
    "a_PD_NMS_12" -> "NMS PD 12",
    "a_PD_NMS_13" -> "NMS PD 13",
    "a_PD_NMS_14" -> "NMS PD 14",
    "a_PD_NMS_15" -> "NMS PD 15",
    "a_PD_NMS_16" -> "NMS PD 16",
    "a_PD_NMS_17" -> "NMS PD 17",
    "a_PD_NMS_18" -> "NMS PD 18",
    "a_PD_NMS_19" -> "NMS PD 19",
    "a_PD_NMS_20" -> "NMS PD 20",
    "a_PD_NMS_21" -> "NMS PD 21",
    "a_PD_NMS_22" -> "NMS PD 22",
    "a_PD_NMS_23" -> "NMS PD 23",
    "a_PD_NMS_24" -> "NMS PD 24",
    "a_PD_NMS_25" -> "NMS PD 25",
    "a_PD_NMS_26" -> "NMS PD 26",
    "a_PD_NMS_27" -> "NMS PD 27",
    "a_PD_NMS_28" -> "NMS PD 28",
    "a_PD_NMS_29" -> "NMS PD 29",
    "a_PD_NMS_30" -> "NMS PD 30",
    "a_PD_NMS_sum" -> "NMS PD Sum",
    "a_PD_NMS_mean" -> "NMS PD Mean",

    "a_MoCa_Exekutiv" -> "MoCa Executive",
    "a_MoCa_Benennen" -> "MoCa Name",
    "a_MoCa_Aufmerksamkeit_Zahlenliste" -> "MoCa Number List",
    "a_MoCa_Aufmerksamkeit_Buchstabenliste" -> "MoCa Attention Number List" ,
    "a_MoCa_Aufmerksamkeit_Abziehen" -> "MoCa Subtracted Attention Test",
    "a_MoCa_Sprache_Wiederholen" -> "MoCa Language Repeat",
    "a_MoCa_Sprache_FWoerter" -> "MoCa Language F Words",
    "a_MoCa_Abstraktion" -> "MoCa Abstraction",
    "a_MoCa_Erinnerung" -> "MoCa Memory",
    "a_MoCa_Orientierung" -> "MoCa Orientation",
    "a_MoCa_Gesamt" -> "MoCa Sum",

    "a_PDSS_1" -> "PDSS 1",
    "a_PDSS_2" -> "PDSS 2",
    "a_PDSS_3" -> "PDSS 3",
    "a_PDSS_4" -> "PDSS 4",
    "a_PDSS_5" -> "PDSS 5",
    "a_PDSS_6" -> "PDSS 6",
    "a_PDSS_7" -> "PDSS 7",
    "a_PDSS_8" -> "PDSS 8",
    "a_PDSS_9" -> "PDSS 9",
    "a_PDSS_10" -> "PDSS 10",
    "a_PDSS_11" -> "PDSS 11",
    "a_PDSS_12" -> "PDSS 12",
    "a_PDSS_13" -> "PDSS 13",
    "a_PDSS_14" -> "PDSS 14",
    "a_PDSS_15" -> "PDSS 15",
    "a_PDSS_sum" -> "PDSS Sum",
    "a_PDSS_mean" -> "PDSS Mean",

    "a_ESS_1" -> "ESS 1",
    "a_ESS_2" -> "ESS 2",
    "a_ESS_3" -> "ESS 3",
    "a_ESS_4" -> "ESS 4",
    "a_ESS_5" -> "ESS 5",
    "a_ESS_6" -> "ESS 6",
    "a_ESS_7" -> "ESS 7",
    "a_ESS_8" -> "ESS 8",
    "a_ESS_sum" -> "ESS Sum",
    "a_ESS_mean" -> "ESS Mean",

    "a_RBD_SQ_1" -> "RBD SQ 1",
    "a_RBD_SQ_2" -> "RBD SQ 2",
    "a_RBD_SQ_3" -> "RBD SQ 3",
    "a_RBD_SQ_4" -> "RBD SQ 4",
    "a_RBD_SQ_5" -> "RBD SQ 5",
    "a_RBD_SQ_6.1" -> "RBD SQ 6.1",
    "a_RBD_SQ_6.2" -> "RBD SQ 6.2",
    "a_RBD_SQ_6.3" -> "RBD SQ 6.3",
    "a_RBD_SQ_6.4" -> "RBD SQ 6.4",
    "a_RBD_SQ_7" -> "RBD SQ 7",
    "a_RBD_SQ_8" -> "RBD SQ 8",
    "a_RBD_SQ_9" -> "RBD SQ 9",
    "a_RBD_SQ_10" -> "RBD SQ 10",
    "a_RBD_SQ_sum" -> "RBD SQ Sum",
    "a_RBD_SQ_mean" -> "RBD SQ Mean"
  )
}